-- CREATE TABLE projects (id INTEGER PRIMARY KEY, title TEXT, category TEXT, funding_goal INTEGER, start_date TEXT, end_date TEXT); 
-- CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT, age INTEGER);
-- CREATE TABLE pledges (id INTEGER PRIMARY KEY, amount INTEGER, user_id INTEGER, project_id INTEGER);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('some name', 'some category', 1000, '10/20/20', '10/21/21');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('some name', 'some category', 1000, '10/20/20', '10/21/21');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('some name', 'some category', 1000, '10/20/20', '10/21/21');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('some name', 'some category', 1000, '10/20/20', '10/21/21');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('some name', 'some category', 1000, '10/20/20', '10/21/21');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('some name', 'some category', 1000, '10/20/20', '10/21/21');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('some name', 'some category', 1000, '10/20/20', '10/21/21');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('some name', 'some category', 1000, '10/20/20', '10/21/21');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('some name', 'some category', 1000, '10/20/20', '10/21/21');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('some name', 'some category', 1000, '10/20/20', '10/21/21');
INSERT INTO users (name, age) VALUES ('Isaac', 24);
INSERT INTO users (name, age) VALUES ('Isaac', 24);
INSERT INTO users (name, age) VALUES ('Isaac', 24);
INSERT INTO users (name, age) VALUES ('Isaac', 24);
INSERT INTO users (name, age) VALUES ('Isaac', 24);
INSERT INTO users (name, age) VALUES ('Isaac', 24);
INSERT INTO users (name, age) VALUES ('Isaac', 24);
INSERT INTO users (name, age) VALUES ('Isaac', 24);
INSERT INTO users (name, age) VALUES ('Isaac', 24);
INSERT INTO users (name, age) VALUES ('Isaac', 24);
INSERT INTO users (name, age) VALUES ('Isaac', 24);
INSERT INTO users (name, age) VALUES ('Isaac', 24);
INSERT INTO users (name, age) VALUES ('Isaac', 24);
INSERT INTO users (name, age) VALUES ('Isaac', 24);
INSERT INTO users (name, age) VALUES ('Isaac', 24);
INSERT INTO users (name, age) VALUES ('Isaac', 24);
INSERT INTO users (name, age) VALUES ('Isaac', 24);
INSERT INTO users (name, age) VALUES ('Isaac', 24);
INSERT INTO users (name, age) VALUES ('Isaac', 24);
INSERT INTO users (name, age) VALUES ('Isaac', 24);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 2);